#!/bin/sh
/home/otso/llvm-project/build/bin/clang -mllvm=-bpf-enable-alias -mllvm=-bpf-enable-alignment -mllvm=-bpf-enable-slp -mllvm=-bpf-enable-fusion -mllvm=-bpf-enable-const-prop -mllvm=-bpf-enable-dce "$@"
# /home/otso/llvm-project/build/bin/clang -mllvm=-bpf-enable-instrumentation -mllvm=-bpf-enable-alias -mllvm=-bpf-enable-alignment -mllvm=-bpf-enable-slp -mllvm=-bpf-enable-fusion -mllvm=-bpf-enable-const-prop -mllvm=-bpf-enable-dce "$@"
# /home/otso/llvm-project/build/bin/clang -mllvm=-bpf-enable-instrumentation "$@"

